apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-configmap
  namespace: backend
data:
  SERVICE_PORT: "8084"
  BOOKING_HOST: "booking"
  BOOKING_PORT: "8001"
  SEARCH_HOST: "search"
  SEARCH_PORT: "8002"
  JAEGER_ENDPOINT: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
  LOKI_ENDPOINT: "http://loki.istio-system.svc.cluster.local:3100/api/prom/push"