---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-hotel
  namespace: backend
spec:
  selector:
    app: mongodb-hotel
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-hotel
  namespace: backend
spec:
  serviceName: mongodb-hotel
  selector:
    matchLabels:
      app: mongodb-hotel
  template:
    metadata:
      labels:
        app: mongodb-hotel
    spec:
      containers:
        - name: mongodb-hotel
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-hotel-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-hotel-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongodb-hotel-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-hotel-storage
          persistentVolumeClaim:
            claimName: mongodb-hotel-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-hotel-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-hotel-pv
  namespace: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo